# Generated by Django 4.2.6 on 2023-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.CharField(default='No description', max_length=200),
        ),
    ]
